{% set name = "cwltool" %}
{% set version = "3.1.20250715140722" %}
{% set sha256 = "1490df44b5508d9f28d70ad380ed73b1af7af7f60406fd8c434701123cbdfb28" %}
package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [py2k or win]
  entry_points:
    - cwltool=cwltool.main:run
  script: CWLTOOL_USE_MYPYC=1 MYPYPATH=mypy-stubs {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # for mypyc
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - mypy ==1.17.0 # setup.py needs this when CWLTOOL_USE_MYPYC=1
    - types-requests
    - types-setuptools
    - types-psutil
    - types-mock
    - setuptools >=45
    - setuptools_scm >=8.0.4,<9
    - schema-salad >=8.9,<9
    - galaxy-tool-util >=22.1.2,<25.1,!=23.0.1,!=23.0.2,!=23.0.3,!=23.0.4,!=23.0.5
    - toml
    - argcomplete >=1.12.0
    - cwl-utils >=0.32
    - ruamel.yaml >=0.17.6,<0.19
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
    - rich-argparse
  run:
    - python
    - requests >=2.6.1
    - ruamel.yaml >=0.17.6,<0.19
    - rdflib >=4.2.2,<7.2.0
    - shellescape >=3.4.1,<3.9
    - schema-salad >=8.9,<9
    - prov ==1.5.1
    - mypy_extensions
    - psutil >=5.6.6
    - coloredlogs
    - galaxy-tool-util >=22.1.2,<25.1,!=23.0.1,!=23.0.2,!=23.0.3,!=23.0.4,!=23.0.5
    - galaxy-util <25.1
    - pillow
    - pydot >=1.4.1
    - pyparsing !=3.0.2
    - argcomplete >=1.12.0
    - cachecontrol
    - cwl-utils >=0.32
    - spython >=0.3.0
    - rich-argparse

test:
  requires:
    - bagit >=1.6.4,<1.10
    - pytest >=6.2,<8.5
    - mock >=2.0.0
    - pytest-mock >=1.10.0
    - pytest-httpserver
    - pytest-retry
    - arcp >=0.2.0
    - pytest-xdist >=3.2.0
    - nodejs
    - jq
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help
    - python -m pytest -n 2 -v --pyargs cwltool -k 'not (test_whoami or test_udocker or TestMpiRun or test_windows_warning or test_biocontainers or test_bioconda or test_modules or test_env_filtering or test_preserve_all or test_basic or test_preserve_single)'
about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
