{% set name = "cwltool" %}
{% set version = "3.1.20230601100705" %}
{% set sha256 = "9a5ce021c80e8c9276003c67caf26f163ce0fc03b3ca8b5828cfdb9a1e263fab" %}
package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - qemu-ld-prefix_preserve.patch

build:
  number: 0
  skip: true  # [py2k or win]
  entry_points:
    - cwltool=cwltool.main:run
  script: CWLTOOL_USE_MYPYC=1 MYPYPATH=mypy-stubs {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # for mypyc
  host:
    - python
    - pip
    - mypy ==1.3.0 # setup.py needs this when CWLTOOL_USE_MYPYC=1
    - types-requests
    - types-setuptools
    - types-psutil
    - types-mock
    - setuptools
    - schema-salad >=8.4,<9
    - cwl-utils >=0.22
    - importlib_resources >=1.4
    - importlib_metadata  # [py<38]
    - ruamel.yaml >=0.17.6,<0.18
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
  run:
    - python
    - setuptools
    - requests >=2.6.1
    - ruamel.yaml >=0.17.6,<0.18
    - rdflib >=4.2.2,<6.4.0
    - shellescape >=3.4.1,<3.9
    - schema-salad >=8.4,<9
    - prov ==1.5.1
    - mypy_extensions
    - psutil >=5.6.6
    - typing_extensions
    - importlib_resources >=1.4
    - importlib_metadata  # [py<38]
    - coloredlogs
    - galaxy-tool-util >=22.1.2,<23
    - pydot >=1.4.1
    - argcomplete
    - cachecontrol
    - cwl-utils >=0.22

test:
  requires:
    - bagit >=1.6.4,<1.9
    - pytest >=6.2,<7.4
    - mock >=2.0.0
    - pytest-mock >=1.10.0
    - pytest-httpserver
    - arcp >=0.2.0
    - pytest-xdist
    - nodejs
    - jq
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help
    - python -m pytest -n 2 -v --pyargs cwltool -k 'not (test_whoami or test_udocker or TestMpiRun or test_windows_warning or test_biocontainers or test_bioconda or test_modules or test_env_filtering or test_preserve_all or test_basic or test_preserve_single)'
about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
