{% set name = "cwltool" %}
{% set version = "1.0.20190603140227" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33a135704165fd48ec3409d94c88499b6dde3b2042f344e7a18faf0c72e7f7ba

build:
  number: 0
  entry_points:
    - cwltool=cwltool.main:run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - bagit >=1.6.4
    - mypy_extensions
    - prov ==1.5.1
    - psutil
    - python
    - rdflib >=4.2.2,<4.3.0
    - requests >=2.6.1
    - ruamel.yaml >=0.12.4,<=0.15.77
    - scandir
    - schema-salad >=4.1,<5
    - setuptools
    - shellescape >=3.4.1,<3.5
    - six >=1.9.0
    - typing_extensions
    - pathlib2 ==2.3.2  # [py27]
    - typing >=3.5.3  # [py27]
    - subprocess32  # [not win and py27]

test:
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help

about:
  home: https://www.commonwl.org/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
