{% set name = "cwltool" %}
{% set version = "3.1.20211103193132" %}
{% set sha256 = "50fa3b0fb31251fbfe42eb79bb976766ed1374f103e01477c2094cc63c3d5117" %}
package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k or win or py==39]
  entry_points:
    - cwltool=cwltool.main:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - requests >=2.6.1
    - ruamel.yaml >=0.12.4,<=0.16.5
    - rdflib >=4.2.2,<4.3.0
    - shellescape >=3.4.1,<3.5
    - schema-salad >=8.1.20210627200047,<9
    - mypy_extensions
    - psutil
    - prov ==1.5.1
    - bagit >=1.6.4
    - typing_extensions
    - coloredlogs
    - pydot >=1.4.1
    - typing >=3.5.3  # [py<35]
    - argcomplete

test:
  requires:
    - pytest
    - mock >=2.0.0
    - pytest-mock >=1.10.0
    - arcp >=0.2.0
    - rdflib-jsonld >=0.4.0
    - nodejs
    - jq
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help
    - python -m pytest --pyargs cwltool -k 'not test_v1_0_position_expression and not TestMpiRun and not test_malformed_reqs and not test_whoami and not test_udocker_should_display_memory_usage'
about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
