{% set name = "cwltool" %}
{% set version = "3.1.20220502060230" %}
{% set sha256 = "c8df57394d2a9b0581444cf6dfa4754047ec20fdb3073c57154f46b205b85758" %}
package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - cwltool=cwltool.main:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - requests >=2.6.1
    - ruamel.yaml >=0.15,<0.17.17
    - rdflib >=4.2.2,<6.1.0
    - shellescape >=3.4.1,<3.9
    - schema-salad >=8.2.20211104054942,<9
    - mypy_extensions
    - psutil >=5.6.6
    - prov ==1.5.1
    - bagit >=1.6.4
    - typing_extensions
    - coloredlogs
    - pydot >=1.4.1
    - argcomplete
    - cachecontrol

test:
  requires:
    - pytest >=6.2,<6.3
    - pytest-xdist
    - mock >=2.0.0
    - pytest-mock >=1.10.0
    - arcp >=0.2.0
    - rdflib-jsonld >=0.4.0
    - nodejs
    - jq
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help
    - python -m pytest -n auto --pyargs cwltool -k 'not (test_whoami or test_udocker_should_display_memory_usage or TestMpiRun)'
about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
