{% set name = "cwltool" %}
{% set version = "3.0.20200530110633" %}
{% set sha256 = "6a40556d2ac7bea17d78a95ad902794c34a9d23568ae0595545a51e232cd9241" %}
package:
  name: cwltool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cwltool/cwltool-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  entry_points:
    - cwltool=cwltool.main:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.12.4,<=0.16.5
    - rdflib >=4.2.2,<4.3.0
    - shellescape >=3.4.1,<3.5
    - schema-salad >=6,<7
    - mypy_extensions
    - psutil
    - prov ==1.5.1
    - bagit >=1.6.4
    - typing_extensions
    - coloredlogs
    - galaxy-tool-util
    # these commented out because they don't seem to be needed any more
    # - scandir
    # - six >=1.9.0
    # - pathlib2 >=2.3.2
    - typing >=3.5.3  # [py<35]

test:
  # these waiting to be enabled when arcp is available in conda
  # requires:
  #   - pytest <6
  #   - mock >=2.0.0
  #   - pytest-mock >=1.10.0
  #   - arcp >=0.2.0
  #   - rdflib-jsonld >=0.4.0
  imports:
    - cwltool
    - cwltool.tests
  commands:
    - cwltool --help
    # - python -m pytest --pyargs cwltool
about:
  home: https://www.commonwl.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Common workflow language reference implementation
  dev_url: https://github.com/common-workflow-language/cwltool
  doc_url: https://github.com/common-workflow-language/cwltool

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
